Vagrant.configure("2") do |config|
  config.vm.hostname = "mysql"
  config.vm.box = "plumelo/xenial64"

  config.vm.provider :lxc do |lxc, override|
    lxc.container_name = "mysql"
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'test.yml'
  end
end

