---

language: python
sudo: required
dist: xenial
python:
  - 2.7
  - 3.7

addons:
  apt:
    update: true
    packages:
      - python-apt
      - python-pycurl

install:
  - pip install ansible
  - pip install ansible-lint==3.5.1

services:
  - mysql

script:
  - ansible-lint test/test.yml
  - ansible-playbook -i test/inventory --syntax-check --list-tasks test/test.yml
  - ansible-playbook -i test/inventory --connection=local --become -vvvv test/test.yml -u root
  - >
      ansible-playbook -i test/inventory --connection=local --become -vvvv test/test.yml -u root
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
