---

- import_tasks: dependencies.yml

- import_tasks: install.yml
  when: mysql_installation_type == ""

- import_tasks: configure.yml

- import_tasks: users.yml
  when: mysql_users is defined and (mysql_users|length)>0

- import_tasks: databases.yml
  when: mysql_databases is defined and (mysql_databases|length)>0
